#language 
lang_perm: "Báº¡n cáº§n quyá»n `MANAGE_GUILD` Ä‘á»ƒ sá»­ dá»¥ng lá»‡nh nÃ y."
lang_arg: "Vui lÃ²ng chá»‰ Ä‘á»‹nh má»™t ngÃ´n ngá»¯! <vi, en>"
provide_lang: "Vui lÃ²ng cung cáº¥p cÃ¡c ngÃ´n ngá»¯: `%{languages}`"
lang_set: "`ğŸ”§` | *NgÃ´n ngá»¯ Ä‘Ã£ Ä‘Æ°á»£c Ä‘áº·t thÃ nh:* `%{language}`"
lang_change: "`ğŸ”§` | *NgÃ´n ngá»¯ Ä‘Ã£ Ä‘Æ°á»£c thay Ä‘á»•i thÃ nh:* `%{language}`"
lang_error: "ÄÃ£ xáº£y ra sá»± cá»‘, vui lÃ²ng thá»­ láº¡i sau."
# prefix
prefix_perm: "Báº¡n cáº§n quyá»n `MANAGE_GUILD` Ä‘á»ƒ sá»­ dá»¥ng lá»‡nh nÃ y."
prefix_arg: "Vui lÃ²ng chá»‰ Ä‘á»‹nh má»™t Prefix!"
prefix_length: "Prefix khÃ´ng Ä‘Æ°á»£c dÃ i hÆ¡n 10 kÃ½ tá»±!"
prefix_set: "`ğŸ”§` | *Prefix Ä‘Ã£ Ä‘Æ°á»£c Ä‘áº·t thÃ nh:* `%{prefix}`"
prefix_change: "`ğŸ”§` | *Prefix Ä‘Ã£ Ä‘Æ°á»£c thay Ä‘á»•i thÃ nh:* `%{prefix}`"
prefix_error: "ÄÃ£ xáº£y ra lá»—i khi Ä‘áº·t Prefix!"
# automusic
hangdoicua: "HÃ ng Ä‘á»£i cá»§a:"
khongconhac: "**Hiá»‡n táº¡i cÃ³ 0 BÃ i hÃ¡t trong HÃ ng Ä‘á»£i**"
debatdauhat: "Báº¯t Ä‘áº§u nghe nháº¡c báº±ng cÃ¡ch káº¿t ná»‘i vá»›i KÃªnh thoáº¡i vÃ  gá»­i **LIÃŠN Káº¾T BÃ€I HÃT** hoáº·c **TÃŠN BÃ€I HÃT** trong KÃªnh nÃ y"
mp3online: "LiÃªn káº¿t Ã¢m thanh vÃ  MP3 trá»±c tiáº¿p"
thattinh: "tháº¥t tÃ¬nh"
dowload_music: "Táº£i Nháº¡c-Danh sÃ¡ch phÃ¡t:"
chuapingkenh: "Báº¡n quÃªn chÆ°a ping kÃªnh vÄƒn báº£n"
success_music: "ÄÃ£ thiáº¿t láº­p thÃ nh cÃ´ng Há»‡ thá»‘ng Ã¢m nháº¡c trong:"
# 